- README.md
- board/raspberrypi0cam/post-build.sh
- package/piwebcam/multi-gadget.sh
- package/piwebcam/piwebcam.mk
- package/piwebcam/piwebcam.service
- package/piwebcam/start-webcam.sh
Also, move the uvc-webcam script to buildroot dir so that we have better
separation between uvc-webcam and its startup logic.
How to override camera settings:
Connect to the ttyACM device and issue
/usr/bin/v4l2-ctl -L | less
Then, create a file called camera.txt in /boot and put all parameters
you want overridden, for example:
auto_exposure_bias=15
> Piwebcam: Enable overriding of camera settings

- README.md
My HQ camera finally arrived today and I was able to test the setup with RPi Zero (non-WiFi) version.
I used `v1.40` release (`sdcard-raspberry0-v1.40.img.gz`) and the camera works as expected.
Many thanks!
> Mark Pi Zero v1.3 (without Wi-Fi) as tested for HQ camera

- .gitignore
- README.md
- board/raspberrypi0cam/genimage-raspberrypi0.cfg
- board/raspberrypi0cam/genimage-raspberrypi0cam.cfg
- board/raspberrypi0cam/post-image.sh
- package/piwebcam/camera.txt
- package/piwebcam/start-webcam.sh
Create a default camera.txt and allow to overwrite it during build time by adding a camera.txt file to the root of the repository
> add default camera.txt which can be overwritten during build

- README.md
`ll` command doesn't exist on MacOS.
Also, I didn't need to run sudo to use `screen`, don't know if that's necessary for sure or not.
> Updated readme with Mac OS example

- package/piwebcam/piwebcam.mk
This is needed to be able to build buildroot with
BR2_PER_PACKAGE_DIRECTORIES. Otherwise piwebcam.service would get
installed as the file /usr/lib/systemd/system rather than as a file
under /usr/lib/systemd/system/ since this directory did not already
exist when building with per-package directories.
Note the man page line about the -D option for install(1):
create all leading components of DEST *except the last*
> piwebcam: Specify full target path to install command

- .github/workflows/release.yml
it seems like that secrets was not available on a global env level, but only during the steps
> fix github actions cache key

- .gitignore
- README.md
- board/genimage-raspberrypi0.cfg
- board/genimage-raspberrypi0w.cfg
- board/post-image.sh
- package/piwebcam/Config.in
- package/piwebcam/multi-gadget.sh
- package/piwebcam/piwebcam.mk
- package/piwebcam/start-webcam.sh
- package/piwebcam/usb-gadget-config.service
- package/piwebcam/uvc-webcam.service
- Separate the logic to initialize usb gadget from uvc-webcam.
- Allow usb serial to be functional when uvc-webcam can't start up.
- Allow user to edit the usb-gadget.txt file to disable serial
access to the Pi.
> Separate usb-gadget-config logic from uvc-webcam

- .github/workflows/release.yml
Currently, every time we build, we hammer the server of our
good friends at Buildroot project. We should not do that, and cache
our extracted tarball.
> Github actions: Cache buildroot

- README.md
It worked for me out of the box, so thought it could get the " &check; " for compatibility.
My environment is Ubuntu 18.04. 
Firefox and Chromium can see the device and the video works fine (used Jitsi to verify)
Great little project, thanks for building it ;)
> Works with pi zero v1.3 + v2 camera module

- .github/workflows/shellcheck.yml
- board/post-image.sh
- Run shellcheck on PRs and releases to prevent silly shell mistakes
- Fix post-image shellcheck warning
> Github actions: Run shellcheck

- package/piwebcam/multi-gadget.sh
- package/piwebcam/usb-gadget-config.service
Ensure udev has settled before we setup the gadget, on the Pi 4 at least this is nice to have, although probably not needed (when camera support is built as a module I've still had it show up late).
Also make sure to enable serial so that logs can be retrieved if we fail to find a camera.
> Multi gadget fixes

- README.md
I tested an official raspberry pi v2 module with a raspberry pi 4b 4gb and it worked without any issues.
I did have to build a raspberry pi 4 image as there where no raspberry pi 4 version under releases?
> Tested v2 camera on raspberry pi 4

- README.md
- patches/linux-custom/0001-linux-enable-more-video-controls.patch
This PR moves the values for usb descriptor `bmControls` bitmap to a commandline parameter, so we can experiment what host OSes expect to see there and what actually works with the Pi cameras, without having to recompile a kernel all the time.
The Bitmap can be changed by editing `cmdline.txt` on the SD to say `usb_f_uvc.bm_controls=<byte1>,<byte2>`.
Submitting as Draft to get it out there, might not yet work on master since it might need support from [uvc-gadget](/peterbay/uvc-gadget), but should help against the issues seen in #116
> Set processing controls from cmdline

- README.md
The tutorial on Cytron is a much easier and more visually appealing to newbies.
> Replace instructions with tutorial link on Cytron

- .github/workflows/release.yml
- README.md
- package/piwebcam/multi-gadget.sh
- package/piwebcam/piwebcam.mk
- package/piwebcam/video_formats.txt
Includes the following changes:
- use [:space:] instead of \s as older versions of grep don't support \s
- remove sed as the busybox version uses different flags than gnu sed
- use awk to parse the resolutions which is less error-prone
- call config_frame before setting up streaming headers as the setup will break otherwise
- update buildroot to 2021.02.4
This replaces PR #128
> Configurable resolutions

- .github/workflows/release.yml
Closes #157 
This PR adds a step that creates a CHECKSUMS file to be uploaded with other assets on release. I do it at the end of the workflow because then we have all assets already present in the same working directory.
My first iteration was using sha512, but I decided to replace it with sha256 for no particular reason.
Please feel free to make any suggestions.
> Add sha256 checksum file to releases

- package/piwebcam/multi-gadget.sh
As per @tomjtobin comment in showmewebcam/showmewebcam#164, `multi-gadget.sh` reports only one configuration but uses container `c.2`.
This causes macOS 12.0.1 to no longer recognise the UVC Camera.
Changing to `c.1` works on macOS 12.0.1 and 11.5.2.
Not tested on other systems.
More information on UVC gadget configuiration: https://www.kernel.org/doc/Documentation/usb/gadget_configfs.txt
> Use c.1 config container instead of c.2. Fixes issue #164

- README.md
- patches/linux-custom/0001-linux-enable-more-video-controls.patch
The values that are currently set by default in the patch for updating the f_uvc.c kernel driver file will try to enable some controls that are not supported by the 8 Mpixel (v2) camera on the RaspberryPi 4B HW and leaves out some that are supported.
Fix the values to match exactly the controls that are possible.
I don't have any other HW than the RPi 4B + v2 camera so I don't know if these settings are completely valid on other HW combinations.
NOTE: In order to get the exposure and white balance controls working, fixes are needed also in the uvc-gadget code.
https://github.com/peterbay/uvc-gadget/pull/23
> Enable only controls that the RPi camera supports

- .github/workflows/release.yml
- .gitignore
- .gitmodules
- README.md
There are several pros to use this git feature:
- no need to download from external site, less steps to start to
build the project
- easy to set a new version of buildroot and keep it updated
- there is risk that the project will not be compatible with newer
versions of buildroot, so the older version of the project
will be rebuildable (starting with this patch)
Let's use version 2021.02.8 as it still buildable with the project.
Signed-off-by: Dmytro Kropenko <k.dmitriu@gmail.com>
> buildroot: use buildroot from official repo as submodule

- .github/workflows/release.yml
- .gitmodules
- board/post-build.sh
This PR does the following:
- Gets the buildroot commit id automatically instead of having to change release.yml every time we change it
- Properly set os-release file with the current showmewebcam version id
- Fixes the sha265sum command
- Uses the full git version description for image file names (ie. sdcard-raspberrypi0-v1.91-12-gffc2ff3.img)
- Switch to the official buildroot repository
> improve build script

- package/camera-control/camera-control.mk
- package/piwebcam/piwebcam.mk
- package/soft-hwclock/soft-hwclock.mk
Unauthorized git:// links are no more supported by Github. Use https:// instead.
https://www.infoq.com/news/2021/09/github-improves-security/
> package: use HTTPS link instead of GIT to download packages

- package/piwebcam/start-webcam.sh
Have the shell process for `start-webcam.sh` directly `exec()` the uvc-gadget, avoiding an extra shell process during the lifetime of the gadget process.
Fixes #182
> Omit fork() before launching uvc-gadget
